//
// Created by sjh_9 on 21/2/2024.
//
#include "catch.hpp"
#include "../helper/AstProgram.cpp"
#include "../helper/PKBStubSP.cpp"
#include "sp/extractor/relation_extractor/ModifiesExtractor.h"
#include "sp/ast/Program.h"

TEST_CASE("Modifies_TestSequentialNestingChain") {
    std::multiset<pair<std::string, std::string>> resultsVector = {
            {"1", "t"},
            {"AssignCallPrintRead", "t"},
            {"2", "x"},
            {"5", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"17", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"18", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"20", "t"},
            {"21", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"20", "t"},
            {"22", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"20", "x"},
            {"24", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"20", "t"},
            {"25", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"27", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"28", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"30", "x"},
            {"31", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"30", "t"},
            {"32", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"30", "x"},
            {"34", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "t"},
            {"6", "t"},
            {"16", "t"},
            {"30", "t"},
            {"35", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "t"},
            {"2", "t"},
            {"7", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"2", "t"},
            {"9", "t"},
            {"10", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"2", "t"},
            {"9", "t"},
            {"11", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"2", "x"},
            {"9", "x"},
            {"13", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"2", "t"},
            {"9", "t"},
            {"14", "t"},
            {"AssignCallPrintRead", "t"},
            {"IfElseWithStmtsBeforeAndInside", "t"},
            {"3", "t"},
            {"AssignCallPrintRead", "t"},
    };
    auto program = AstProgram::createSequentialNestingChain();
    auto pkb = make_shared<PKBStubSP>();
    shared_ptr<ProgramVisitor> extractor = std::make_shared<ModifiesExtractor>(pkb, program);
    for (const auto& procedure : *program->getProcedures()) {
        procedure->accept(*extractor);
    }
    REQUIRE(pkb->checkAgainstPairResults(resultsVector));
}