//
// Created by sjh_9 on 21/2/2024.
//
#include "catch.hpp"
#include "../helper/AstTestProgramProducer.h"
#include "../helper/PkbStubSp.cpp"
#include "sp/extractor/relation_extractor/UsesExtractor.h"
#include "sp/ast/Program.h"

inline AstTestProgramProducer astPrograms = AstTestProgramProducer();

TEST_CASE("Uses_TestSequentialIfIfNestingChain") {
    std::multiset<pair<std::string, std::string>> resultsVector = {
            {"1", "y"},
            {"AssignCallPrintRead", "y"},
            {"1", "y"},
            {"AssignCallPrintRead", "y"},
            {"2", "y"},
            {"5", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"17", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"6", "u"},
            {"16", "u"},
            {"19", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"20", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"20", "y"},
            {"21", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"20", "y"},
            {"21", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"6", "u"},
            {"16", "u"},
            {"20", "u"},
            {"23", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"20", "y"},
            {"24", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"6", "u"},
            {"16", "u"},
            {"20", "u"},
            {"26", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"27", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"6", "u"},
            {"16", "u"},
            {"29", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "x"},
            {"6", "x"},
            {"16", "x"},
            {"30", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"30", "y"},
            {"31", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"6", "u"},
            {"16", "u"},
            {"30", "u"},
            {"33", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "y"},
            {"6", "y"},
            {"16", "y"},
            {"30", "y"},
            {"34", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"6", "u"},
            {"16", "u"},
            {"30", "u"},
            {"36", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"IfElseWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "u"},
            {"8", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"2", "x"},
            {"9", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"9", "y"},
            {"10", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"2", "y"},
            {"9", "y"},
            {"10", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"9", "u"},
            {"12", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"2", "y"},
            {"9", "y"},
            {"13", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"9", "u"},
            {"15", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithStmtsBeforeAndInside", "u"},
            {"4", "u"},
            {"AssignCallPrintRead", "u"},
    };
    auto program = astPrograms.createSequentialIfIfNestingChain();
    auto pkb = make_shared<PkbStubSp>();
    shared_ptr<ProgramVisitor> extractor = std::make_shared<UsesExtractor>(pkb, program);
    for (const auto& procedure : *program->getProcedures()) {
        procedure->accept(*extractor);
    }
    REQUIRE(pkb->checkAgainstPairResults(resultsVector));
}

TEST_CASE("Uses_TestSequentialIfWhileNestingChain") {
    std::multiset<pair<std::string, std::string>> resultsVector = {
            {"1", "y"},
            {"AssignCallPrintRead", "y"},
            {"1", "y"},
            {"AssignCallPrintRead", "y"},
            {"2", "x"},
            {"5", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"5", "y"},
            {"6", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "y"},
            {"5", "y"},
            {"7", "y"},
            {"24", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
            {"WhileWithStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"5", "u"},
            {"7", "u"},
            {"26", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
            {"WhileWithStmtsBeforeAndInside", "u"},
            {"2", "x"},
            {"5", "x"},
            {"7", "x"},
            {"27", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
            {"WhileWithStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"5", "y"},
            {"7", "y"},
            {"27", "y"},
            {"28", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
            {"WhileWithStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"5", "u"},
            {"7", "u"},
            {"27", "u"},
            {"30", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
            {"WhileWithStmtsBeforeAndInside", "u"},
            {"2", "u"},
            {"5", "u"},
            {"9", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "x"},
            {"5", "x"},
            {"10", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"5", "y"},
            {"10", "y"},
            {"11", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"5", "u"},
            {"10", "u"},
            {"14", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "y"},
            {"5", "y"},
            {"15", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"5", "u"},
            {"18", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
            {"2", "x"},
            {"5", "x"},
            {"19", "x"},
            {"AssignCallPrintRead", "x"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
            {"2", "y"},
            {"5", "y"},
            {"19", "y"},
            {"20", "y"},
            {"AssignCallPrintRead", "y"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
            {"2", "u"},
            {"5", "u"},
            {"19", "u"},
            {"23", "u"},
            {"AssignCallPrintRead", "u"},
            {"IfElseWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
            {"4", "u"},
            {"AssignCallPrintRead", "u"},
    };
    auto program = astPrograms.createSequentialIfWhileNestingChain();
    auto pkb = make_shared<PkbStubSp>();
    shared_ptr<ProgramVisitor> extractor = std::make_shared<UsesExtractor>(pkb, program);
    for (const auto& procedure : *program->getProcedures()) {
        procedure->accept(*extractor);
    }
    REQUIRE(pkb->checkAgainstPairResults(resultsVector));
}


TEST_CASE("Uses_TestSequentialWhileIfNestingChain") {
    std::multiset<pair<std::string, std::string>> resultsVector = {
        {"1", "y"},
        {"AssignCallPrintRead", "y"},
        {"1", "y"},
        {"AssignCallPrintRead", "y"},
        {"2", "x"},
        {"5", "x"},
        {"AssignCallPrintRead", "x"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
        {"2", "y"},
        {"5", "y"},
        {"6", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
        {"2", "y"},
        {"5", "y"},
        {"7", "y"},
        {"19", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
        {"WhileWithStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"7", "u"},
        {"21", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
        {"WhileWithStmtsBeforeAndInside", "u"},
        {"2", "x"},
        {"5", "x"},
        {"7", "x"},
        {"22", "x"},
        {"AssignCallPrintRead", "x"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
        {"WhileWithStmtsBeforeAndInside", "x"},
        {"2", "y"},
        {"5", "y"},
        {"7", "y"},
        {"22", "y"},
        {"23", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
        {"WhileWithStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"7", "u"},
        {"22", "u"},
        {"25", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
        {"WhileWithStmtsBeforeAndInside", "u"},
        {"2", "u"},
        {"5", "u"},
        {"9", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
        {"2", "x"},
        {"5", "x"},
        {"10", "x"},
        {"AssignCallPrintRead", "x"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "x"},
        {"2", "y"},
        {"5", "y"},
        {"10", "y"},
        {"11", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"10", "u"},
        {"14", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
        {"2", "y"},
        {"5", "y"},
        {"10", "y"},
        {"15", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"10", "u"},
        {"18", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedIfElsePlusNestedStmtsBeforeAndInside", "u"},
        {"4", "u"},
        {"AssignCallPrintRead", "u"},
    };
    auto program = astPrograms.createSequentialWhileIfNestingChain();
    auto pkb = make_shared<PkbStubSp>();
    shared_ptr<ProgramVisitor> extractor = std::make_shared<UsesExtractor>(pkb, program);
    for (const auto& procedure : *program->getProcedures()) {
        procedure->accept(*extractor);
    }
    REQUIRE(pkb->checkAgainstPairResults(resultsVector));
}

TEST_CASE("Uses_TestSequentialWhileWhileNestingChain") {
    std::multiset<pair<std::string, std::string>> resultsVector = {
        {"1", "y"},
        {"AssignCallPrintRead", "y"},
        {"1", "y"},
        {"AssignCallPrintRead", "y"},
        {"2", "x"},
        {"5", "x"},
        {"AssignCallPrintRead", "x"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
        {"2", "y"},
        {"5", "y"},
        {"6", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
        {"2", "y"},
        {"5", "y"},
        {"7", "y"},
        {"15", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
        {"WhileWithStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"7", "u"},
        {"17", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
        {"WhileWithStmtsBeforeAndInside", "u"},
        {"2", "x"},
        {"5", "x"},
        {"7", "x"},
        {"18", "x"},
        {"AssignCallPrintRead", "x"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
        {"WhileWithStmtsBeforeAndInside", "x"},
        {"2", "y"},
        {"5", "y"},
        {"7", "y"},
        {"18", "y"},
        {"19", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
        {"WhileWithStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"7", "u"},
        {"18", "u"},
        {"21", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
        {"WhileWithStmtsBeforeAndInside", "u"},
        {"2", "u"},
        {"5", "u"},
        {"9", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
        {"2", "x"},
        {"5", "x"},
        {"10", "x"},
        {"AssignCallPrintRead", "x"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "x"},
        {"2", "y"},
        {"5", "y"},
        {"10", "y"},
        {"11", "y"},
        {"AssignCallPrintRead", "y"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "y"},
        {"2", "u"},
        {"5", "u"},
        {"10", "u"},
        {"14", "u"},
        {"AssignCallPrintRead", "u"},
        {"WhileWithNestedWhilePlusNestedStmtsBeforeAndInside", "u"},
        {"4", "u"},
        {"AssignCallPrintRead", "u"},
    };
    auto program = astPrograms.createSequentialWhileWhileNestingChain();
    auto pkb = make_shared<PkbStubSp>();
    shared_ptr<ProgramVisitor> extractor = std::make_shared<UsesExtractor>(pkb, program);
    for (const auto& procedure : *program->getProcedures()) {
        procedure->accept(*extractor);
    }
    REQUIRE(pkb->checkAgainstPairResults(resultsVector));
}