# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Windows CMake Build and Unit Test

on:
  push:
    branches: [ "cicd" , "master" ]
  pull_request:
    branches: [ "cicd" , "master" ]
  workflow_dispatch:
    name: Run Windows Build

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{github.workspace}}/Team05/Code05/ -B ${{github.workspace}}/Team05/Code05/cmake-cli -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build(AutoTester)
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/Team05/Code05/cmake-cli --target autotester --config ${{env.BUILD_TYPE}}

    - name: Build(Unit Testing)
      if: false
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/Team05/Code05/cmake-cli --target unit_testing --config ${{env.BUILD_TYPE}}

    - name: Upload Artifact (Unit Testing)
      if: false
      uses: actions/upload-artifact@v4
      with:
          name: unit_testing.exe
          path: ${{github.workspace}}/Team05/Code05/cmake-cli/src/unit_testing/Debug/unit_testing.exe

    - name: Upload Artifact (AutoTester)
      uses: actions/upload-artifact@v4
      with:
          name: autotester.exe
          path: ${{github.workspace}}/Team05/Code05/cmake-cli/src/autotester/Debug/autotester.exe

  unit-test:
    if: false
    runs-on: windows-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: unit_testing.exe
        path: ${{github.workspace}}/Team05/Code05/cmake-cli/src/unit_testing/Debug
        
    - name: Unit Test
      # runs unit test
      run: ${{github.workspace}}/Team05/Code05/cmake-cli/src/unit_testing/Debug/unit_testing.exe

  system-test:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autotester.exe
          path: ${{github.workspace}}/Team05/Code05/cmake-cli/src/autotester/Debug

      - name: run system test script
        working-directory: Team05/Tests05
        run: python3 run-tests.py

      - name: Upload Artifact (Test Results)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results.zip
          path: '${{github.workspace}}/Team05/Tests05/results/results.zip'
